@path = http://localhost:8080

### verifica versao
GET {{path}}

### get jogadores
GET {{path}}/api/v1/jogadores

### upsert jogadores
POST {{path}}/api/v1/jogadores
Content-Type: application/json

{
    
    "celular": "31999878433",
    "email": "teste@teste.com",
    "nome": "MATEUS",
    "cpf": "10125554613"
}
