@path = http://localhost:8080

### verifica versao
GET {{path}}

### upsert jogadores
POST {{path}}/api/v1/jogadores
Content-Type: application/json

{
    
    "celular": "1",
    "email": "1",
    "nome": "1",
    "ranking": "1",
    "posicaoRanking": "1"
}